version: "3"
services:
  dispatcher:
    build: .
    container_name: test_dispatcher
    environment:
      - AEM_PORT=80
      - AEM_HOST=nginx
    volumes:
        - ./src:/mnt/dev/src
    ports:
      - 8080:80
    links:
      - nginx
    networks:
      - backend
  nginx:
    image: aemdesign/nginx
    container_name: test_dispatcher_renderer
    ports:
      - 8081:80
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
