#!/bin/sh
set -e

if [ -f /usr/sbin/envvars ]; then
  . /usr/sbin/envvars
fi

if [ "$ENABLE_MANAGED_REWRITE_MAPS_FLAG" = "true" ]; then
  /usr/sbin/managed-rewrite-maps-empty-init "${APACHE_PREFIX}"
fi

exec su-exec "${APACHE_USER}:${APACHE_GROUP}" httpd -t -D DUMP_VHOSTS -f /etc/httpd/conf/httpd.conf
